// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5XB2To5iIsnZrxnCHkM4YCXs2BYAO-_0',
    appId: '1:151175368190:web:73a60cb83e0419f9e884af',
    messagingSenderId: '151175368190',
    projectId: 'coffeshop-95d4d',
    authDomain: 'coffeshop-95d4d.firebaseapp.com',
    storageBucket: 'coffeshop-95d4d.appspot.com',
    measurementId: 'G-PY58VW7Z01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBikgS3AM7TsJH0EBsgUC5B4fcmUXe_Y2o',
    appId: '1:151175368190:android:3947195047c06554e884af',
    messagingSenderId: '151175368190',
    projectId: 'coffeshop-95d4d',
    storageBucket: 'coffeshop-95d4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8wLSQaDpBxdfqKjcuCZhKNxbs8ukUms',
    appId: '1:151175368190:ios:9a1d0e240bc06b42e884af',
    messagingSenderId: '151175368190',
    projectId: 'coffeshop-95d4d',
    storageBucket: 'coffeshop-95d4d.appspot.com',
    iosBundleId: 'com.example.coffeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB8wLSQaDpBxdfqKjcuCZhKNxbs8ukUms',
    appId: '1:151175368190:ios:269c86231b88cb08e884af',
    messagingSenderId: '151175368190',
    projectId: 'coffeshop-95d4d',
    storageBucket: 'coffeshop-95d4d.appspot.com',
    iosBundleId: 'com.example.coffeShop.RunnerTests',
  );
}
